name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  t8_dependencies:
    strategy:
      fail-fast: false
      matrix:
        docker_os: [ubuntu]
        compiler: [gcc, clang]
        include:
          - runner_os: ubuntu-latest
    runs-on: ${{ matrix.runner_os }}
    steps:
    - uses: actions/checkout@v2
    - name: Build the docker image
      run: |
        docker build --tag dlramr/t8code-dependencies:t8-dependencies-${{ matrix.docker_os }}-${{ matrix.compiler }} dependencies/${{ matrix.docker_os }}/${{ matrix.compiler }}
    - name: Push the docker image
      env: # Set the secret as an input
        docker_token: ${{ secrets.DOCKER_TOKEN }}
      run: |
        echo ${{ env.docker_token }} | docker login --username dlramr --password-stdin
        docker push dlramr/t8code-dependencies:t8-dependencies-${{ matrix.docker_os }}-${{ matrix.compiler }}
