name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include: 
          - os: ubuntu-latest
            target_os: ubuntu
            tag: t8-dependencies
            t8code_version: 0
          - os: ubuntu-latest
            target_os: ubuntu
            tag: t8-1.0.0
            t8code_version: 1.0.0
          - os: ubuntu-latest
            target_os: ubuntu
            tag: t8-1.1.0
            install_t8code: 1
            t8code_version: 1.1.0
          - os: ubuntu-latest
            target_os: ubuntu
            tag: t8-1.2.0
            t8code_version: 1.2.0
    runs-on: ${{ matrix.os }} 
    steps:
    - uses: actions/checkout@v2
    - name: Build the docker image
      run: |
        docker build --build-arg t8code_version=${{ matrix.t8code_version}} --tag dlramr/t8code-${{ matrix.target_os }}:${{ matrix.tag }} ${{ matrix.target_os }}
    - name: Push the docker image
      env: # Set the secret as an input
        docker_token: ${{ secrets.DOCKER_TOKEN }}
      run: |
        docker login -u dlramr -p ${{ env.docker_token }}
        docker push dlramr/t8code-${{ matrix.target_os }}:${{ matrix.tag }}
